name: egphysio_clinic_admin
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.6.2+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Commons
  nb_utils: ^7.1.3
  google_fonts: ^6.2.1
  html: ^0.15.5
  http: ^1.3.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_vector_icons: ^2.0.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  stream_transform: ^2.1.1
  flutter_local_notifications: ^17.2.3
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  responsive_navigation_bar: ^5.0.2
  date_picker_timeline: ^1.2.6
  signature: ^5.4.1
  syncfusion_flutter_charts: ^29.1.33
  expandable_page_view: ^1.0.17
  datepicker_dropdown: ^0.1.6
  pro_image_editor: ^6.1.6
  table_calendar: ^3.0.9

  #firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  permission_handler: ^11.4.0
  path_provider: ^2.1.5

  # State Management
  get: ^4.7.2

  #Storage
  get_storage: ^2.1.1

  #PhotoViewGallery
  photo_view: ^0.15.0

  #Pickers
  file_picker: ^9.2.1
  image_picker: ^1.1.2
  country_picker: ^2.0.27
  flutter_time_picker_spinner: ^2.0.0

  # Google Map
  google_maps_flutter: ^2.12.0
  geolocator: ^13.0.3
  geocoding: ^3.0.0

  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2

  qr_code_scanner_plus: ^2.0.10+1
  flutter_native_splash: ^2.4.4

  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon.png"
  image_path: 'assets/icon/icon.png'
  ios: true
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: "assets/icons/splashIcon12-.png"
  branding: "assets/icons/brandingIcon12-.png"
  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: "assets/icons/splashIcon12+.png"
    branding: "assets/icons/brandingIcon12+.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/icons/navigation/
    - assets/icons/social_media/